name: mobile
description: "Flutter mobile application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_ui_auth: ^1.15.0
  firebase_ui_localizations: ^1.12.0
  firebase_ui_oauth_google: ^1.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.20.5
  go_router: ^14.2.2
  google_sign_in: ^6.2.1
  grpc: ^4.0.0
  hooks_riverpod: ^2.5.1
  protobuf: ^3.1.0
  riverpod_annotation: ^2.3.5
  flutter_dotenv: ^5.1.0
  flutter_expandable_fab: ^2.2.0
  freezed_annotation: ^2.4.4
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  go_router_builder: ^2.7.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.7
  flutter_gen_runner: ^5.6.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
